# Generated by Django 4.2.4 on 2023-09-28 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inst', '0002_alter_institutionuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='institutionuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='username',
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='institution_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
