# Generated by Django 4.2.4 on 2023-09-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0003_alter_institutionuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionuser',
            name='groups',
        ),
    ]
