# Generated by Django 4.2.4 on 2023-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplicationnotification',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarshipapplicationnotification',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
