# Generated by Django 4.2.4 on 2023-09-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_rename_state_id_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='id',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
